name: BrdyOrn
description: Turning &#x1F355; into code
url: http://brdyorn.com

collections:
  projects:
    output: true
  slides:
    output: true

markdown: kramdown
highlighter: rouge
assets:
  dirname: assets
  baseurl: /assets/
  sources:
    - _assets/images
    - _assets/fonts
    - _assets/javascript
    - _assets/stylesheets
  js_compressor: uglifier
  css_compressor: sass
